# Generated by Django 4.2.11 on 2024-04-02 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[("[('carro', 'Carro'), ('moto', 'Moto')]", 'Automoveis')], max_length=50)),
                ('vagas', models.IntegerField(default=0)),
                ('limite_vagas', models.IntegerField(default=0)),
                ('caroneiros', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Alunos que estão pegando carona')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Motorista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
