# Generated by Django 4.2.11 on 2024-04-02 17:50

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField()),
                ('quem_avaliou', models.IntegerField(verbose_name='ID de quem Avaliou')),
                ('tipo_avaliacao', models.CharField(choices=[('motorista', 'Motorista'), ('caroneiro', 'Caroneiro')], max_length=30)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Ponto de Encontro')),
                ('x', models.CharField(max_length=25, verbose_name='Coordenada X do ponto de encontro')),
                ('y', models.CharField(max_length=25, verbose_name='Coordenada Y do ponto de encontro')),
            ],
        ),
        migrations.AlterField(
            model_name='carona',
            name='tipo',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], max_length=50),
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20)),
                ('comprovante', models.FileField(upload_to=core.models.get_upload_path)),
                ('curso', models.CharField(max_length=100)),
                ('automovel', models.CharField(max_length=200, verbose_name='Qual o automóvel dirigido:')),
                ('carona_paga', models.BooleanField(default=True, verbose_name='Precisa pagar pela carona?')),
                ('custo', models.FloatField(default=0.0, verbose_name='Custo pela carona')),
                ('horario_saida', models.CharField(max_length=10, verbose_name='Horário de Saída para o Destino')),
                ('horario_volta', models.CharField(max_length=10, verbose_name='Horário de Volta para o Ponto de Saída')),
                ('matricula_valida', models.BooleanField(default=True)),
                ('ponto_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ponto')),
            ],
        ),
        migrations.CreateModel(
            name='Caroneiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20)),
                ('comprovante', models.FileField(upload_to=core.models.get_upload_path)),
                ('curso', models.CharField(max_length=100)),
                ('matricula_valida', models.BooleanField(default=True)),
                ('ponto_encontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ponto')),
            ],
        ),
        migrations.AlterField(
            model_name='carona',
            name='caroneiros',
            field=models.ManyToManyField(to='core.caroneiro', verbose_name='Alunos que estão pegando carona'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Motorista', to='core.motorista'),
        ),
    ]
