# Generated by Django 4.2.11 on 2024-04-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_metodopagamento_motorista_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deslocamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField()),
                ('hora_ida', models.IntegerField()),
                ('hora_volta', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='horario_saida',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='horario_volta',
        ),
        migrations.AlterField(
            model_name='motorista',
            name='custo',
            field=models.FloatField(default=0.0, verbose_name='Custo pela carona ida e volta/dia'),
        ),
        migrations.CreateModel(
            name='Combinado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ida', models.BooleanField(default=False)),
                ('volta', models.BooleanField(default=False)),
                ('dia_semana', models.IntegerField()),
                ('caroneiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caroneiro')),
            ],
        ),
        migrations.AddField(
            model_name='carona',
            name='combinados',
            field=models.ManyToManyField(to='core.combinado', verbose_name='Dias e horarios de idas conjuntas dos motoristas e caroneiros'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='deslocamentos',
            field=models.ManyToManyField(to='core.deslocamento'),
        ),
    ]
