# Generated by Django 4.2.11 on 2024-04-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_deslocamento_remove_motorista_horario_saida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deslocamento',
            name='hora_ida',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='deslocamento',
            name='hora_volta',
            field=models.TimeField(),
        ),
    ]
