# Generated by Django 4.2.11 on 2024-04-04 21:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_deslocamento_hora_ida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20)),
                ('comprovante', models.FileField(upload_to=core.models.get_upload_path)),
                ('curso', models.CharField(max_length=100)),
                ('from_username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='caroneiro',
            name='ponto_encontro',
        ),
    ]
