# Generated by Django 4.2.11 on 2024-04-04 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_temporario_remove_caroneiro_ponto_encontro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='ponto_saida',
        ),
        migrations.AddField(
            model_name='deslocamento',
            name='ponto_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deslocamentos_destino', to='core.ponto'),
        ),
        migrations.AddField(
            model_name='deslocamento',
            name='ponto_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deslocamentos_saida', to='core.ponto'),
        ),
        migrations.AlterField(
            model_name='caroneiro',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='matricula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
