# Generated by Django 4.2.11 on 2024-04-04 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_solicitacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='enviado_para_tipo',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='enviado_por_tipo',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='enviado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 4, 23, 54, 36, 102815, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='visualizada',
            field=models.BooleanField(default=False),
        ),
    ]
