# Generated by Django 4.2.11 on 2024-04-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_solicitacao_enviado_para_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='aceitar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
