# Generated by Django 4.2.11 on 2024-04-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_solicitacao_aceitar'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='enviado_para_tipo',
            field=models.CharField(choices=[('caroneiro', 'Caroneiro'), ('motorista', 'Motorista')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='enviado_por_tipo',
            field=models.CharField(choices=[('caroneiro', 'Caroneiro'), ('motorista', 'Motorista')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
