# Generated by Django 4.2.11 on 2024-04-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_solicitacao_enviado_para_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='caroneiros',
            field=models.ManyToManyField(blank=True, null=True, to='core.caroneiro', verbose_name='Alunos que estão pegando carona'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='combinados',
            field=models.ManyToManyField(blank=True, null=True, to='core.combinado', verbose_name='Dias e horarios de idas conjuntas dos motoristas e caroneiros'),
        ),
    ]
