# Generated by Django 4.2.11 on 2024-04-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_carona_caroneiros_alter_carona_combinados'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='avaliado',
            field=models.IntegerField(default=0, verbose_name='ID de quem foi Avaliado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
