# Generated by Django 4.2.11 on 2024-04-08 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_alter_avaliacao_tipo_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=50)),
                ('valor_transacao', models.FloatField(default=0)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pagante', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recebedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField(default=0)),
                ('movimentacao', models.ManyToManyField(to='core.movimentacao')),
            ],
        ),
    ]
