# Generated by Django 4.2.11 on 2024-04-08 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_extrato_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='data_movimentacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 8, 17, 23, 25, 784487, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
