# Generated by Django 4.2.11 on 2024-04-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_movimentacao_data_movimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deslocamento',
            name='dia_semana',
            field=models.CharField(choices=[('segunda', 'Segunda'), ('terça', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta')], max_length=20),
        ),
    ]
