# Generated by Django 4.2.11 on 2024-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_deslocamento_ponto_destino_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
    ]
