# Generated by Django 4.2.11 on 2024-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_endereco_caroneiro_endereco_motorista_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
            preserve_default=False,
        ),
    ]
