# Generated by Django 4.2.11 on 2024-04-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_combinado_dia_semana_combinado_deslocamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinado',
            name='ponto_encontro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ponto_encontro', to='core.ponto'),
        ),
    ]
