# Generated by Django 4.2.11 on 2024-04-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_combinado_ponto_encontro'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinado',
            name='endereco_ponto_encontro',
            field=models.CharField(default='Rua Fernando Ferrari', max_length=250),
            preserve_default=False,
        ),
    ]
