# Generated by Django 4.2.11 on 2024-04-18 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_combinado_endereco_ponto_encontro'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinado',
            name='horario_encontro_ponto_encontro',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
