# Generated by Django 4.2.11 on 2024-04-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_combinado_horario_encontro_ponto_encontro'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='deslocamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deslocamento'),
        ),
    ]
