# Generated by Django 4.2.11 on 2024-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_solicitacao_conteudo_solicitacao_deslocamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('carona', 'Carona'), ('combinado', 'Combinado')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
