# Generated by Django 4.2.11 on 2024-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_mensagem_conversa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='mensagens',
            field=models.ManyToManyField(blank=True, null=True, to='config.mensagem'),
        ),
    ]
