# Generated by Django 4.2.11 on 2024-04-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_conexao_conversa_conexoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='conexoes',
            field=models.ManyToManyField(blank=True, to='config.conexao'),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='mensagens',
            field=models.ManyToManyField(blank=True, to='config.mensagem'),
        ),
    ]
