# Generated by Django 4.2.11 on 2024-04-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_conversa_conexoes_alter_conversa_mensagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
    ]
